services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    container_name: cli-proxy-api
    restart: unless-stopped
    # pull_policy: always
    user: "950:544"
    networks:
      external:
        ipv4_address: 192.168.5.235
    ports:
      - "8317:8317"
      - "8085:8085"
      - "1455:1455"
      - "54545:54545"
      - "51121:51121"
      - "11451:11451"
    volumes:
      - /mnt/performance/docker/cliproxyapi/CLIProxyAPI/config.yaml:/CLIProxyAPI/config.yaml
      - /mnt/performance/docker/cliproxyapi/CLIProxyAPI/auths:/CLIProxyAPI/auths
      - /mnt/performance/docker/cliproxyapi/CLIProxyAPI/logs:/CLIProxyAPI/logs
      - /mnt/performance/docker/cliproxyapi/CLIProxyAPI/static:/CLIProxyAPI/static
    environment:
      - MANAGEMENT_STATIC_PATH=/CLIProxyAPI/static

networks:
  external:
    external: true
